### ISSUE TITLE
tricks crash game (1.19 phi dev version)

### ISSUE THREAD

**Issue by ANT83z4** [gdavid04/phi#25] opened 2024-03-15 20:49 UTC
if the elastic anchor or accelerate contain caster as entity that the spell affect game crashes
{modsRequired:[{modName:"phi",modVersion:"1.19-DEV"},{modName:"psi",modVersion:"2.0.0"}],spellList:[{data:{constantValue:"40",key:"psi:constant_number"},x:4,y:4},{data:{key:"psi:selector_caster"},x:5,y:2},{data:{key:"psi:operator_list_add",params:{_list:0,_target:1}},x:5,y:3},{data:{key:"phi:trick_elastic_anchor",params:{_power:2,_target:1,_time:3}},x:5,y:4},{data:{constantValue:"0.23",key:"psi:constant_number"},x:5,y:5},{data:{key:"phi:constant_vector",x:"0",y:"1",z:"0"},x:6,y:4}],spellName:"Elastic Anchor",uuidLeast:-4654938175331326171L,uuidMost:7196226152018889148L,validSpell:1b}
[2024-03-14-2.log.gz](https://github.com/gdavid04/phi/files/14620624/2024-03-14-2.log.gz)
[2024-03-14-4.log.gz](https://github.com/gdavid04/phi/files/14620625/2024-03-14-4.log.gz)
so all 3 accelerate tricks (on mobs no crahs but player yes)
eidos anchor doesnt crash on any mobs i tried so far
(the correct crash log all in one file below)

**Comment by ANT83z4** [comment] 2024-03-15 21:32
[latest.log](https://github.com/gdavid04/phi/files/14620927/latest.log)
this is the correct crash log. (crash to main menu mod confused me)

**Comment by gdavid04** [comment] 2024-03-15 21:46
Caused by https://github.com/gdavid04/phi/blob/7b469f4b0a81693763c62ab469edc5af496181d0/src/main/java/gdavid/phi/capability/AccelerationCapability.java#L78-L79

**Comment by ANT83z4** [comment] 2024-03-15 23:52
[crash-2024-03-16_00.49.53-client.txt](https://github.com/gdavid04/phi/files/14621637/crash-2024-03-16_00.49.53-client.txt)
so apparently summon marker decided to crash again

{modsRequired:[{modName:"phi",modVersion:"1.19-DEV"},{modName:"psi",modVersion:"2.0.0"}],spellList:[{data:{constantValue:"20",key:"psi:constant_number"},x:2,y:3},{data:{key:"psi:trick_delay",params:{_time:4}},x:2,y:5},{data:{key:"phi:selector_nearby_markers",params:{_position:0,_radius:0}},x:2,y:6},{data:{key:"phi:trick_conjure_marker",params:{_position:4,_time:3}},x:3,y:3},{data:{constantValue:"2",key:"psi:constant_number"},x:3,y:5},{data:{key:"psi:trick_debug_spamless",params:{_number:0,_target:3}},x:3,y:6},{data:{key:"psi:operator_vector_sum",params:{_vector1:4,_vector2:2,_vector3:0}},x:4,y:3},{data:{key:"psi:operator_entity_position",params:{_target:2}},x:4,y:4},{data:{key:"psi:connector",params:{_target:4}},x:4,y:5},{data:{constantValue:"31",key:"psi:constant_number"},x:5,y:2},{data:{key:"psi:operator_vector_multiply",params:{_number2:1,_vector1:2}},x:5,y:3},{data:{key:"psi:operator_entity_look",params:{_target:2}},x:5,y:4},{data:{key:"psi:selector_caster"},x:5,y:5}],spellName:"Conjure Marker",uuidLeast:-7961046074445064172L,uuidMost:3079199197529525938L,validSpell:1b}

**Comment by gdavid04** [comment] 2024-04-15 13:28
Fixed in 6b2a369a06eb5ee5d1f29369442796743cb265c8 and f9778f87480bfa641431370c04fd89af2033a44d

**Closed as completed by gdavid04** 2024-04-15 13:28 UTC
Labels: bug, high priority, 1.19
